### ISSUE TITLE
TwoWire' has no member named 'end' (ESP8266 and ESP32)

### ISSUE THREAD

**Issue by cmfrancis** [sparkfun/SparkFun_Qwiic_Keypad_Arduino_Library#1]
For documentation:
When trying to compile code for this library, the following error is generated for ESP8266 and ESP32 based boards.

error: 'class TwoWire' has no member named 'end'
     _i2cPort->end();

**Comment by nseidle** [comment]
@lewispg228 @AndyEngland521 Looks like you guys are cargo culting code from somewhere.

https://github.com/sparkfun/SparkFun_Qwiic_Joystick_Arduino_Library/blob/master/src/SparkFun_Qwiic_Joystick_Arduino_Library.cpp#L65

https://github.com/sparkfun/SparkFun_Qwiic_Keypad_Arduino_Library/blob/master/src/SparkFun_Qwiic_Keypad_Arduino_Library.cpp

Why are you ending I2C hardware on the master when changing the address of a slave? I don't think you need to.

**Comment by santaimpersonator** [comment]
Hey @nseidle, I added those [lines](https://github.com/sparkfun/SparkFun_Qwiic_Joystick_Arduino_Library/blob/master/src/SparkFun_Qwiic_Joystick_Arduino_Library.cpp#L65):

    _i2cPort->end();
    delay(100);

After we first started to set the brown-out detection fuse bits, the response from the library wasn't acting very consistent with the board. In debugging the issue, I ended up adding a delay and later including the close of the hardware connection to get better results. I can add an `#if` statement to fix the compilation issue. It looks like wire library for the AVR, Mega, and SAMD cores all support the `end()` function, the exception is the Espressif cores for the ESP8266 and ESP32.

I agree that line shouldn't be necessary, but it seemed to provide more consistent results in the address change function. If I add an `#if` statement to fix the compilation issue, would it be preferable to just exclude the ESP cores for that line?

**Comment by lewispg228** [comment]
I removed the end() and created [release v1.1.0](https://github.com/sparkfun/SparkFun_Qwiic_Keypad_Arduino_Library/releases/tag/v1.1.0). 

Verified on three sets of hardware: atmega328 (redboard qwiic), esp8266 thing and a esp32 thing dev.
