### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by zyphlar** [sparkfun/SparkFun_Qwiic_Keypad_Arduino_Library#3]
The library CPP and H files say "GNU General Public License" but LICENSE.md says MIT and CC-SA-4.0.

It's really important to be clear about what is and isn't GPL licensed since there are significant obligations imposed upon GPL software. Could these files be updated to be clear about what license(s) they're released under?

**Comment by sfe-SparkFro** [comment]
Hi there! Apologies for the unclear and conflicting licenses. All software from SparkFun is meant to use the MIT license (as indicated by LICENSE.md), so I've updated the header comments to match (555e4a6). Thank you for bringing this to our attention!
